name: enable_workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'https://github.com/xin053/actions'

      - name: Enable workflow
        run: gh workflow list | awk '{print $1}' | xargs -i gh workflow enable {}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
